version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8118:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8008:8008"
    environment:
      JWT_SECRET: abcdefghijklmnopqrstuvwxyz0123456789
      MONGO_URI: mongodb://mongo:27017/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"

volumes:
  mongodata:
